SELECT 
idEvaluationListeRouge AS 'internal_taxon_id', 
DureeGenerationnelle AS 'generationlength.range', 
PopulationReductionPasse AS 'PopulationReductionPast.range', 
PopulationReductionFutur AS'PopulationReductionFuture.range', 
PopulationReductionFuturETPasse AS 'PopulationReductionPastandFuture.range', 
CausePopulationReductionPasse AS'PopulationReductionPastBasis.value', 
CausePopulationReductionFutur AS 'PopulationReductionFutureBasis.value', 
CauseReductionPasseETFutur AS 'PopulationReductionPastandFutureBasis.value',
ReductionPopulationPasseCauseComprise AS'PopulationReductionPastUnderstood.value',
ReductionPopulationPasseCauseReversible AS'PopulationReductionPastReversible.value',
ReductionPopulationPasseCauseFin AS'PopulationReductionPastCeased.value',
ReductionPopulationPasseFuturCauseComprise AS'PopulationReductionPastandFutureUnderstood.value',
ReductionPopulationPasseFuturCauseReversible AS'PopulationReductionPastAndFutureReversible.value',
ReductionPopulationPasseFuturCauseFin AS'PopulationReductionPastAndFutureCeased.value', 
EOO AS 'EOO.range', 
AOO AS 'AOO.range', 
AltitudeMinimale AS 'ElevationLower.limit', 
AltitudeMaximale AS'ElevationUpper.limit', 
NombreSousPopulation AS 'maxsubpopulationsize.range', 
NombreLocalite AS 'LocationsNumber.range', 
NombreLocaliteJustification AS 'LocationsNumber.justification', 
FragmentationSevere AS 'SevereFragmentation.isFragmented', 
PopulationTailleIndMature AS'PopulationSize.range', 
DeclinContinuAOO AS 'AOOContinuingDecline.isInContinuingDecline', 
DeclinContinuEOO AS 'EOOContinuingDecline.isContinuingDecline', 
DeclinContinuLocaliteSousPopulation AS 'LocationContinuingDecline.InDecline', 
DeclinContinuIndMature AS 'PopulationContinuingDecline.isDeclining',  
DeclinContinuHabitat AS 'HabitatContinuingDecline.IsDeclining', 
DeclinContinuAOOQualificatif AS 'AOOContinuingDecline.qualifier', 
DeclinContinuEOOQualificatif AS 'EOOContinuingDecline.qualifier', 
DeclinContinuNombreLocaliteSsPopulationQualificatif AS 'LocationContinuingDecline.qualifier', 
DeclinContinuIndMatureQualificatif AS 'PopulationContinuingDecline.qualifier', 
DeclinContinuHabitatQualificatif AS 'HabitatContinuingDecline.qualifier', 
FluctuationExtremeAOO AS 'AOOExtremeFluctuation.is Fluctuating', 
FluctuationExtremeEOO AS 'EOOExtremeFluctuation.is Fluctuating', 
FluctuationExtremeNombreLocalite AS 'LocationExtremeFluctuation.is Fluctuating', 
FluctuationExtremeIndMature AS 'PopulationExtremeFluctuation.is Fluctuating', 
FluctuationExtremeSousPopulation AS 'SubpopulationExtremeFluctuation.is Fluctuating', 
ProbabiliteExtinctionGeneration3 AS 'ExtinctionProbabilityGenerations3.range', 
ProbabiliteExtinctionGeneration5 AS 'ExtinctionProbabilityGenerations5.range', 
ProbabiliteExtinctionAnnee100 AS 'ExtinctionProbabilityYears100.range', 
NonUtilisationEspece AS 'NotUtilized.isNotUtilized', 
NonInformationUtilisationCommercialisationEspece AS 'UseTradeNoInformation.value', 
NonConsommationEspece AS 'NonConsumptiveUse.isNonConsumptiveUse', 
NonInformationSubsistanceEspece AS 'Livelihoods.noInfo', 
NonExistenceMenace AS'NoThreats.noThreats', 
MenaceInconnue AS 'threatsunknown.value',
PresentAireProtegee AS 'InPlaceLandWaterProtectionInPA.value',
ConservationExSitu AS'InPlaceSpeciesmanagementExSitu.value',
GestionEspeceEnvahissante AS 'InPlaceLandWaterProtectionInvasiveControl.value',
ReussiteReIntroduction AS 'InPlaceSpeciesmanagementReintroduced.value'

FROM evaluationlisterouge
WHERE AireEvaluation = 'Global' AND (DateEvaluation ='2015-07-23' OR DateEvaluation='2015-07-24') AND CategorieEvaluation != 'NE';